#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "Task2.h" // Includes TreeNode definition
#include "Task1.h" // For Stack, pop(), isEmpty() (the string token stack)

// --- Private Helper Prototypes ---

/**
 * @brief Allocates and initializes a new TreeNode.
 * @param value The string value for the node (will be copied).
 * @return A pointer to the new TreeNode.
 */
static TreeNode* makeNode(const char *value);

/**
 * @brief Checks if a token is a binary operator.
 * @param token The string token to check.
 * @return true if it's a binary operator, false otherwise.
 */
static bool isBinary(const char *token);

/**
 * @brief Checks if a token is a unary operator.
 * @param token The string token to check.
 * @return true if it's a unary operator, false otherwise.
 */
static bool isUnary(const char *token);

/**
 * @brief Recursive helper function for printing the tree vertically.
 * @param root The current node to print.
 * @param prefix The line prefix (for indentation and connectors).
 * @param isLastChild true if this node is the last child of its parent.
 */
static void printTreeRecursiveHelper(TreeNode *root, const char *prefix, bool isLastChild);

// === Stack for TreeNodes (used by iterative builder) ===

/**
 * @brief A simple stack structure for holding TreeNode pointers.
 * @note This is a separate stack implementation from the one in Task1.
 * It's used by the iterative prefixToTree algorithm to keep
 * track of parent nodes that are waiting for children.
 */
typedef struct {
    TreeNode** data; // Array of TreeNode pointers
    int top;         // Index of the top element
    int capacity;    // Max size of the stack
} NodeStack;

/**
 * @brief Creates a new stack for TreeNode pointers.
 * @param capacity The maximum number of nodes the stack can hold.
 * @return A pointer to the new NodeStack. Exits on allocation failure.
 */
static NodeStack* createNodeStack(int capacity) {
    NodeStack* ns = (NodeStack*)malloc(sizeof(NodeStack));
    if (!ns) { fprintf(stderr, "Failed to allocate NodeStack\n"); exit(1); }
    ns->data = (TreeNode**)malloc(sizeof(TreeNode*) * capacity);
    if (!ns->data) { fprintf(stderr, "Failed to allocate NodeStack data\n"); free(ns); exit(1); }
    ns->capacity = capacity;
    ns->top = -1; // Stack is initially empty
    return ns;
}

/**
 * @brief Checks if the NodeStack is empty.
 * @param ns The NodeStack.
 * @return 1 (true) if empty, 0 (false) otherwise.
 */
static int isNodeStackEmpty(NodeStack* ns) { return ns->top == -1; }

/**
 * @brief Peeks at the top TreeNode* of the stack without removing it.
 * @param ns The NodeStack.
 * @return The top TreeNode*, or NULL if the stack is empty.
 */
static TreeNode* node_peek(NodeStack* ns) { return (ns->top >= 0) ? ns->data[ns->top] : NULL; } 

/**
 * @brief Pushes a TreeNode* onto the stack.
 * @note Does not check for overflow (assumes capacity is sufficient).
 * @param ns The NodeStack.
 * @param node The TreeNode pointer to push.
 */
static void node_push(NodeStack* ns, TreeNode* node) { ns->data[++ns->top] = node; }

/**
 * @brief Pops a TreeNode* from the stack.
 * @param ns The NodeStack.
 * @return The popped TreeNode*, or NULL if the stack is empty.
 */
static TreeNode* node_pop(NodeStack* ns) { return (ns->top >= 0) ? ns->data[ns->top--] : NULL; }

/**
 * @brief Frees the memory used by the NodeStack (but not the TreeNodes it points to).
 * @param ns The NodeStack to free.
 */
static void freeNodeStack(NodeStack* ns) { free(ns->data); free(ns); }
// === END: NodeStack ===


// --- Public Function Definitions ---

/**
 * @brief Helper to check if a token is an atom (operand).
 * An atom is any token that is not a known operator.
 * @param token The string token to check.
 * @return true if the token is an atom, false otherwise.
 */
bool isAtom(const char *token) {
    if (!token || token[0] == '\0') return false;
    // It's an atom if it's NOT a known operator
    return !(isBinary(token) || isUnary(token));
}

/**
 * @brief Iteratively builds a parse tree from a prefix expression stack.
 *
 * This algorithm works by processing tokens one by one from the prefix stack
 * (which was generated by `task1_infixToPrefix`). It uses a *second* stack
 * (`NodeStack`) to keep track of parent nodes (operators) that are
 * waiting to be assigned children.
 *
 * @param prefix_stack The stack of prefix tokens (from Task1).
 * @return A pointer to the root TreeNode of the constructed parse tree.
 */
TreeNode* prefixToTree(Stack *prefix_stack) {
    if (prefix_stack == NULL || isEmpty(prefix_stack)) {
        return NULL; // Nothing to build
    }

    // 1. Get the first token: this must be the root of the tree.
    char* token = pop(prefix_stack);
    if (!token) return NULL;
    TreeNode* root = makeNode(token);
    free(token); // makeNode creates a copy

    // Node stack stores parent nodes waiting for children
    NodeStack* node_stack = createNodeStack(prefix_stack->capacity);

    // 2. If the root is an operator, it needs children.
    // Push it onto the node_stack to wait for them.
    if (!isAtom(root->data)) {
        node_push(node_stack, root);
    }

    // 3. Process remaining tokens from the prefix (string) stack
    while (!isEmpty(prefix_stack)) {
        // Get the parent node that's waiting for its *next* child.
        // We *peek* because it might need another child after this one.
        TreeNode* current_parent = node_peek(node_stack);
        
        // Error check: If no parent is waiting, but we have tokens,
        // the expression is malformed (too many operands).
        if (current_parent == NULL) {
             fprintf(stderr, "Error: Node stack empty but prefix stack has tokens (Malformed expression? Too many operands?).\n");
             while ((token = pop(prefix_stack)) != NULL) free(token); // Cleanup remaining tokens
             break; // Exit loop
        }

        // Get the next token from the input (this will be a child)
        token = pop(prefix_stack);
        if (!token) break; // Should not happen if loop condition is correct
        TreeNode* new_node = makeNode(token);
        free(token); // makeNode copies it

        // 4. Attach new_node to parent based on parent type
        bool attached = false;
        if (isUnary(current_parent->data)) {
            // Unary operator ('~') only gets a right child
            if (current_parent->right == NULL) {
                current_parent->right = new_node;
                // A unary parent is now "full" after one child.
                node_pop(node_stack); // Pop it from the waiting stack.
                attached = true;
            } else {
                 // This case should logically not be reachable
                 fprintf(stderr, "Error logic: Unary node '%s' trying to attach second child '%s'?\n", current_parent->data, new_node->data);
                 freeTree(new_node); break; // Error state
            }
        } else if (isBinary(current_parent->data)) {
            // Binary operator ('*', '+', '>') gets left child, then right child.
            if (current_parent->left == NULL) {
                // This is the first child; attach it to the left.
                current_parent->left = new_node;
                attached = true;
                // *Don't* pop parent yet, it still needs a right child.
            } else if (current_parent->right == NULL) {
                // This is the second child; attach it to the right.
                current_parent->right = new_node;
                // A binary parent is now "full" after two children.
                node_pop(node_stack); // Pop it from the waiting stack.
                attached = true;
            } else {
                 // This case should logically not be reachable
                 fprintf(stderr, "Error logic: Binary node '%s' trying to attach third child '%s'?\n", current_parent->data, new_node->data);
                 freeTree(new_node); break; // Error state
            }
        } else {
             // This should not happen, as only operators are pushed to node_stack
             fprintf(stderr, "Error logic: Atom node '%s' on node_stack?\n", current_parent->data);
             freeTree(new_node); break; // Error state
        }

        // 5. If the new node we just attached is *also* an operator,
        // push it onto the node_stack. It will now be the next node
        // waiting for *its* children.
        if (attached && !isAtom(new_node->data)) {
            node_push(node_stack, new_node);
        } else if (!attached) {
            // If we somehow didn't attach (error case), free the new node
            freeTree(new_node);
        }
    } // --- End of while loop ---

    // 6. Final Checks and Cleanup
    
    // If the node_stack is not empty, the expression was malformed
    // (e.g., " + a " -> missing an operand).
    if (!isNodeStackEmpty(node_stack)) {
         fprintf(stderr, "Warning: Node stack not empty after processing all tokens (Malformed expression? Operators missing operands?).\n");
         // Tree might be incomplete.
    }
    // This check is technically redundant with the one inside the loop,
    // but serves as a final safeguard.
     if (!isEmpty(prefix_stack)) {
         fprintf(stderr, "Warning: Prefix stack not empty after processing (Malformed expression? Too many operands?).\n");
         while ((token = pop(prefix_stack)) != NULL) free(token); // Cleanup
     }

    freeNodeStack(node_stack); // Free the helper stack
    return root; // Return the completed tree
}


// --- Functions below remain the same ---

/**
 * @brief Public function to print the tree in a vertical, human-readable format.
 * @param root The root of the tree to print.
 */
void printTreeVertical(TreeNode *root) {
    if (root == NULL) {
        printf("Tree is empty.\n");
        return;
    }
    printf("\nParse Tree Structure:\n");
    printf("%s\n", root->data); // Print the root node
    
    // Call the recursive helper to print children
    if (isUnary(root->data)) {
        // Unary node: only print the right child
        printTreeRecursiveHelper(root->right, "", true); 
    } else {
        // Binary or atom node
        printTreeRecursiveHelper(root->left, "", false); // Left child
        printTreeRecursiveHelper(root->right, "", true);  // Right child
    }
}

/**
 * @brief Recursively frees all nodes in the tree.
 * @param root The root of the tree/subtree to free.
 */
void freeTree(TreeNode *root) {
    if (root == NULL) {
        return; // Base case: empty subtree
    }
    // Recurse on children first (post-order traversal)
    freeTree(root->left);
    freeTree(root->right);
    
    // Free the string data (which was copied with strdup)
    free(root->data); 
    // Free the node structure itself
    free(root);       
}

// --- Private Helper Implementations ---

/**
 * @brief Allocates and initializes a new TreeNode.
 * @param value The string value for the node (will be copied).
 * @return A pointer to the new TreeNode.
 */
static TreeNode* makeNode(const char *value) {
    // Allocate memory for the node structure
    TreeNode* node = (TreeNode*)malloc(sizeof(TreeNode));
    if (!node) {
        fprintf(stderr, "Memory allocation failed for TreeNode.\n");
        exit(EXIT_FAILURE); // Critical failure
    }
    
    // Allocate memory and *copy* the string value
    node->data = strdup(value); 
    if (!node->data) {
        fprintf(stderr, "Memory allocation failed for TreeNode data.\n");
        free(node);
        exit(EXIT_FAILURE); // Critical failure
    }

    // Initialize children to NULL
    node->left = NULL;
    node->right = NULL;
    return node;
}

/**
 * @brief Checks if a token is a binary operator.
 * @param token The string token to check.
 * @return true if it's a binary operator, false otherwise.
 */
static bool isBinary(const char *token) {
    if (!token || strlen(token) != 1) return false; // Must be a single char
    char c = token[0];
    return (c == '+' || c == '*' || c == '>');
}

/**
 * @brief Checks if a token is a unary operator.
 * @param token The string token to check.
 * @return true if it's a unary operator, false otherwise.
 */
static bool isUnary(const char *token) {
    if (!token || strlen(token) != 1) return false; // Must be a single char
    char c = token[0];
    return (c == '~');
}

/**
 * @brief Recursive helper function for printing the tree vertically.
 * This function creates the "ASCII art" connectors.
 * @param root The current node to print.
 * @param prefix The line prefix (indentation and connectors like "    " or "|   ").
 * @param isLastChild true if this node is the last child of its parent
 * (determines if we use '`--' or '|--').
 */
static void printTreeRecursiveHelper(TreeNode *root, const char *prefix, bool isLastChild) {
    if (root == NULL)
        return; // Base case: empty child

    // Determine the connector string
    const char *connector = isLastChild ? "`-- " : "|-- ";
    // Print the current node
    printf("%s%s%s\n", prefix, connector, root->data);

    // Prepare the prefix for the *next* level of recursion
    char newPrefix[512]; // Buffer for the new prefix
    
    // Append to the prefix: "    " if last child, "|   " otherwise
    snprintf(newPrefix, sizeof(newPrefix)-1, "%s%s", prefix, (isLastChild ? "    " : "|   ")); 
    newPrefix[sizeof(newPrefix)-1] = '\0'; // Guarantee null termination

    // Recursively print children
    if (isUnary(root->data)) {
        // Unary node only has a right child
        // We treat it as the "last" child for connector purposes
        printTreeRecursiveHelper(root->right, newPrefix, true); 
    } else {
        // Binary node or Atom (Atom's children will be NULL, recursion will stop)
        printTreeRecursiveHelper(root->left, newPrefix, false); // Left child is not the last
        printTreeRecursiveHelper(root->right, newPrefix, true); // Right child is the last
    }
}